# Generated by Django 3.1.7 on 2021-03-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meetingDescription',
        ),
    ]
