# Generated by Django 3.1.7 on 2021-03-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmanagement', '0003_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='meetingId',
            new_name='participantMeeting',
        ),
    ]
