# Generated by Django 3.1.7 on 2021-03-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmanagement', '0004_auto_20210301_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='participantMeeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainmanagement.meeting'),
        ),
    ]
