# Generated by Django 3.1.7 on 2021-03-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmanagement', '0005_auto_20210301_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='participantMeeting',
        ),
        migrations.AddField(
            model_name='participants',
            name='participantMeetingId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
