# Generated by Django 3.1.7 on 2021-03-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmanagement', '0006_auto_20210301_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='participantMeetingId',
            new_name='participantMeeting',
        ),
    ]
